### PR TITLE
updated /soup dependency

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**
@seveibar did I need to do this step? Because I did bun update this dependency in core and it didn't update it's own dependencies

### CODE REVIEW

**Comment by seveibar** [comment]
you shouldn't need to update it, if you update soup in core it should update the types here, everything will kind of magically work

**Comment by seveibar** [comment]
if something isn't working, you can run `npm ls @tscircuit/soup` which will show you if somehow two copies got installed

**Comment by ShiboSoftwareDev** [comment]
image
 @seveibar

**Comment by seveibar** [comment]
yea something is wrong, soup-util shouldn't have it's own version

**Comment by seveibar** [comment]
Let's try making some package.json changes here to fix it

image

**Comment by seveibar** [comment]
also `transformation-matrix` should be a dependency rather than a dev dependency

**Review by seveibar — APPROVED** [review]
lgtm, you might want to do a quick test with `yalc` to make sure it doesn't break things but i think this is correct!!

**Pull request merged**
